[package]
name = "xml2csv"
version = "0.1.0"
authors = ["Clément Renault <renault.cle@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1.2.1"
main_error = "0.1.0"
quick-xml = "0.28.1"
smallstr = "0.2.0"
smallvec = "1.2.0"
time = "0.3.20"
