[package]
name = "xml2csv"
version = "0.1.0"
authors = ["Clément Renault <renault.cle@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1.1.3"
main_error = "0.1.0"
quick-xml = "0.17.2"
smallstr = "0.2.0"
